client/urls.py
"""
URL configuration for client app.
"""

from django.urls import path

from client.views import (ClientDashboardView,
                          BrowseArticlesView,
                          ArticleDetailView,
                          SubscriptionPlansView,
                          CreateSubscriptionView,
                          DeleteSubscriptionView,
                          UpdateSubscriptionView,
                          PayPalSubConfirmedView,
                          DjangoSubConfirmedView)

app_name = 'client'

urlpatterns = [
    path('dashboard/', ClientDashboardView.as_view(), name='dashboard'),
    path('browse-articles/', BrowseArticlesView.as_view(), name='browse-articles'),

    path(
        'subscription-plans/',
        SubscriptionPlansView.as_view(),
        name='subscription-plans'
    ),

    path('article-detail/<slug:slug>/', ArticleDetailView.as_view(), name='article-detail'),

    path(
        'create-subscription/',
        CreateSubscriptionView.as_view(),
        name='create-subscription'),

    path(
        'delete-subscription/<str:subID>/',
        DeleteSubscriptionView.as_view(),
        name='delete-subscription'
    ),

    path(
        'update-subscription/<str:subID>/',
        UpdateSubscriptionView.as_view(),
        name='update-subscription'
    ),

    path(
        'paypal-subscription-confirmed/',
        PayPalSubConfirmedView.as_view(),
        name='paypal-subscription-confirmed'
    ),

    path(
        'django-subscription-confirmed/<str:subID>/',
        DjangoSubConfirmedView.as_view(),
        name='django-subscription-confirmed'
    ),
]

subplatform/urls.py
"""
URL configuration for subplatform project.
"""

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
       path('admin/', admin.site.urls),
       path('', include('account.urls')),
       path('client/', include('client.urls', namespace='client')),
       path('writer/', include('writer.urls', namespace='writer')),
]

writer/urls.py
"""
URL configuration for writer app.
"""

from django.urls import path

from writer.views import (WriterDashboardView,
                          CreateArticleView,
                          MyArticlesView,
                          UpdateArticleView,
                          delete_article)

app_name = 'writer'

urlpatterns = [
    path(
        '<int:writer_id>/dashboard/',
        WriterDashboardView.as_view(),
        name='dashboard'
    ),
    path(
        '<int:writer_id>/create-article/',
        CreateArticleView.as_view(),
        name='create_article'
    ),
    path(
        '<int:writer_id>/my-articles/',
        MyArticlesView.as_view(),
        name='my_articles'
    ),
    path(
        '<int:writer_id>/update-article/<slug:slug>/',
        UpdateArticleView.as_view(),
        name='update_article'
    ),
    path(
        '<int:writer_id>/delete-article/<slug:slug>/',
        delete_article,
        name='delete_article'
    ),
]

writer/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify



class Article(models.Model):
    title = models.CharField(max_length=150)
    slug = models.SlugField(max_length=255, blank=True)
    content = models.TextField(max_length=10000, blank=True)
    author = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )
    date_posted = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    is_premium = models.BooleanField(
        default=False,
        verbose_name="Is it a premium article?"
    )

    class Meta:
        verbose_name = 'article'
        verbose_name_plural = 'articles'
        unique_together = ('slug', 'author')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Article, self).save(*args, **kwargs)

writer/forms.py
from django import forms

from writer.models import Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'slug', 'content', 'is_premium']

writer/views.py
from django.views import View
from django.views.generic import TemplateView, ListView

from django.shortcuts import render, reverse, redirect, get_object_or_404

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from writer.forms import ArticleForm
from writer.models import Article


class WriterDashboardView(TemplateView):
    template_name = 'writer/writer_dashboard.html'

    @method_decorator(login_required(
        login_url='login',
        redirect_field_name='redirect_to'
    ))
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_writer:
            return super(WriterDashboardView, self).dispatch(
                request,
                request.user.id,
                *args, **kwargs
            )

        return redirect('client:dashboard')


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Edenthought | Writer Dashboard'
        return context


class CreateArticleView(LoginRequiredMixin, View):
    login_url = 'login'
    redirect_field_name = 'redirect_to'

    def get(self, request, writer_id):  # noqa
        form = ArticleForm()
        context = {
            'article_form': form,
            'title': 'Edenthought | Create Article'
        }

        return render(request, 'writer/create_article.html', context=context)


    def post(self, request, writer_id):  # noqa
        user = get_user_model().objects.get(id=self.request.user.id)
        form = ArticleForm(request.POST)

        if form.is_valid():
            article = form.save(commit=False)
            article.author = user
            article.save()
            messages.success(request, 'Article created successfully!')
            return redirect(reverse('writer:my_articles', kwargs={'writer_id': writer_id}))

        messages.error(request, 'Something went wrong!')
        return redirect(request.META.get(
            'HTTP_REFERER',
            reverse('writer:my_articles',
            kwargs={'writer_id': self.request.user.id})))


class MyArticlesView(LoginRequiredMixin, ListView):
    login_url = 'login'
    redirect_field_name = 'redirect_to'
    model = Article
    template_name = 'writer/my_articles.html'
    context_object_name = 'articles'

    def dispatch(self, request, *args, **kwargs):
        return super(MyArticlesView, self).dispatch(
            request,
            self.kwargs['writer_id'],
            *args, **kwargs
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Edenthought | My Articles'
        return context

    def get_queryset(self):
        return (super().get_queryset().filter(author=self.request.user)
                .order_by('-date_posted'))


class UpdateArticleView(LoginRequiredMixin, View):
    login_url = 'login'
    redirect_field_name = 'redirect_to'

    def get(self, request, writer_id, slug):  # noqa
        user = get_object_or_404(get_user_model(), id=self.request.user.id)
        article = get_object_or_404(Article, slug=slug, author=user)
        form = ArticleForm(instance=article)
        context = {
            'article_form': form,
            'title': 'Edenthought | Update Article',
            'article': article
        }
        return render(request, 'writer/update_article.html', context=context)

    def post(self, request, writer_id, slug):  # noqa
        user = get_object_or_404(get_user_model(), id=self.request.user.id)
        article = get_object_or_404(Article, slug=slug, author=user)
        form = ArticleForm(request.POST, instance=article)

        if form.is_valid():
            form.save()
            messages.success(request, 'Article updated successfully!')
            return redirect(reverse('writer:my_articles',
                                    kwargs={'writer_id': self.request.user.id}))

        messages.error(request, 'Article update failed! Invalid data has been submitted.')
        return redirect(request.META.get(
            'HTTP_REFERER',
            reverse('writer:my_articles',
            kwargs={'writer_id': self.request.user.id}))
        )


@login_required(redirect_field_name='redirect_to', login_url='login')
def delete_article(request, writer_id, slug):
    user = get_object_or_404(get_user_model(), id=request.user.id)
    try:
        article = Article.objects.get(slug=slug, author=user)
        article.delete()
        messages.success(request, 'Article deleted successfully!')
    except Article.DoesNotExist:
        messages.info(request, 'Article not found.')

    return redirect(reverse('writer:my_articles',
                            kwargs={'writer_id': request.user.id}))

writer/templates/writer/create_article.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block menu %}
  {% include 'writer/includes/writer_menu.html' %}
{% endblock %}

{% block content %}

  <div class="container shadow form-layout my-4 my-md-5 p-5">

    <h3 class="text-center">Create an article</h3>

    <form action="{% url 'writer:create_article' user.id %}" method="post" autocomplete="off" class="pt-2 mt-2 mt-md-4">
      {% csrf_token %}
      {{ article_form|crispy }}
      <input type="submit" value="Create" class="btn btn-success mt-2 mt-md-4">
    </form>

  </div>

{% endblock %}

writer/templates/writer/my_articles.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block menu %}
  {% include 'writer/includes/writer_menu.html' %}
{% endblock %}

{% block content %}

  <div class="container shadow bg-white my-4 my-md-5 pt-4 pb-3">

    <h3 class="text-center">My Articles</h3>

  </div>

  {% if articles %}
    {% for article in articles %}

      <div class="container shadow bg-white my-3 my-md-4 p-4 form-layout">
        <a href="{% url 'client:article-detail' article.slug%}">
          <h3> {{ article.title }} </h3>

          {% if article.is_premium %}
            <h6>🪙 Premium article 🪙</h6>
          {% endif %}

          <br>
          <div>{{ article.content|slice:"0:150" }} ...</div>

          <br>
          <div class="datetime">
            {{ article.date_posted|date:"M j, Y" }} - {{ article.date_posted|time:"H:i:s" }}
          </div>
        </a>

        <div class="update">
          <div>
            <a href="{% url 'writer:update_article' user.id article.slug %}">
              ⚙️ Update article
            </a>
          </div>

          <div class="delete-article">
            <a type="button" data-toggle="modal" data-target="#deleteModalCenter">
              🚫 Delete article
            </a>
          </div>
        </div>

        {% include 'writer/includes/delete_modal.html' %}

      </div>

    {% endfor %}
  {% endif %}


{% endblock %}

writer/templates/writer/update_article.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block menu %}
  {% include 'writer/includes/writer_menu.html' %}
{% endblock %}

{% block content %}

  <div class="container shadow form-layout my-4 my-md-5 p-5">

    <h3 class="text-center">Update Article</h3>

    <form action="{% url 'writer:update_article' user.id article.slug %}"
          method="post"
          autocomplete="off"
          class="pt-2 mt-2 mt-md-4">
      {% csrf_token %}
      {{ article_form|crispy }}
      <input type="submit" value="Update" class="btn btn-success mt-2 mt-md-4">
    </form>

  </div>

{% endblock %}

writer/templates/writer/writer_dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block menu %}
  {% include 'writer/includes/writer_menu.html' %}
{% endblock %}

{% block content %}

  <div class="container bg-white shadow mt-2 mt-md-4 p-5 form-layout text-center">
    <h5>✍️ Welcome, {{ user.first_name }}!</h5>
  </div>

{% endblock %}