client/urls.py
"""
URL configuration for client app.
"""

from django.urls import path

from client.views import (ClientDashboardView,
                          BrowseArticlesView,
                          ArticleDetailView,
                          SubscriptionPlansView,
                          CreateSubscriptionView,
                          DeleteSubscriptionView,
                          UpdateSubscriptionView,
                          PayPalSubConfirmedView,
                          DjangoSubConfirmedView)

app_name = 'client'

urlpatterns = [
    path('dashboard/', ClientDashboardView.as_view(), name='dashboard'),
    path('browse-articles/', BrowseArticlesView.as_view(), name='browse-articles'),

    path(
        'subscription-plans/',
        SubscriptionPlansView.as_view(),
        name='subscription-plans'
    ),

    path('article-detail/<slug:slug>/', ArticleDetailView.as_view(), name='article-detail'),

    path(
        'create-subscription/',
        CreateSubscriptionView.as_view(),
        name='create-subscription'),

    path(
        'delete-subscription/<str:subID>/',
        DeleteSubscriptionView.as_view(),
        name='delete-subscription'
    ),

    path(
        'update-subscription/<str:subID>/',
        UpdateSubscriptionView.as_view(),
        name='update-subscription'
    ),

    path(
        'paypal-subscription-confirmed/',
        PayPalSubConfirmedView.as_view(),
        name='paypal-subscription-confirmed'
    ),

    path(
        'django-subscription-confirmed/<str:subID>/',
        DjangoSubConfirmedView.as_view(),
        name='django-subscription-confirmed'
    ),
]

subplatform/urls.py
"""
URL configuration for subplatform project.
"""

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
       path('admin/', admin.site.urls),
       path('', include('account.urls')),
       path('client/', include('client.urls', namespace='client')),
       path('writer/', include('writer.urls', namespace='writer')),
]

client/models.py
from django.db import models

from django.contrib.auth import get_user_model


class SubscriptionPlan(models.Model):
    paypal_plan_id = models.CharField(max_length=255, unique=True, default="")
    name = models.CharField(max_length=255, unique=True)
    cost = models.DecimalField(decimal_places=2, max_digits=5)
    description = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = 'subscription plan'
        verbose_name_plural = 'subscription plans'

    def __str__(self):
        return f'{self.name}'


class Subscription(models.Model):
    subscriber_name = models.CharField(max_length=255)
    subscription_plan = models.ForeignKey(
        SubscriptionPlan,
        on_delete=models.CASCADE,
        related_name='subscription_plan'
    )
    paypal_subscription_id = models.CharField(max_length=300)
    user = models.OneToOneField(
        get_user_model(),
        on_delete=models.CASCADE,
        related_name='subscription',
        max_length=10,
        unique=True
    )
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return (f'{self.subscriber_name} - '
                f'{self.subscription_plan.name.capitalize()} subscription')

client/views.py
from django.contrib.gis.gdal.prototypes.srs import new_ct
from django.db import IntegrityError
from django.shortcuts import redirect, reverse, get_object_or_404

from django.views.generic import (TemplateView,
                                  ListView,
                                  DetailView,
                                  RedirectView,
                                  View)

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from django.utils.decorators import method_decorator

from writer.models import Article

from client.models import Subscription, SubscriptionPlan
from client.exceptions import SubscriptionNotDeletedException
from client.paypal import (get_access_token,
                           cancel_subscription_paypal,
                           update_subscription_paypal,
                           get_current_subscription_plan)


class ClientDashboardView(LoginRequiredMixin, TemplateView):
    template_name = 'client/client_dashboard.html'
    login_url = 'login'
    redirect_field_name = 'redirect_to'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user.is_writer:  # noqa
            return redirect(reverse(
                'writer:dashboard',
                kwargs={'writer_id': request.user.id}
            ))

        return super(ClientDashboardView, self).dispatch(request, *args, **kwargs)


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        subscriptions = Subscription.objects.filter(
            user=self.request.user,
            is_active=True
        ).order_by('-id')

        if subscriptions.exists():
            context['sub_plan'] = subscriptions[0].subscription_plan

        context['title'] = 'Edenthought | Dashboard'

        return context


class BrowseArticlesView(LoginRequiredMixin, ListView):
    login_url = 'login'
    redirect_field_name = 'redirect_to'

    template_name = 'client/browse-articles.html'

    queryset = Article.objects.all().order_by('-date_posted')
    context_object_name = 'articles'

    def get_queryset(self):
        user = self.request.user
        if not hasattr(user, 'subscription') or not user.subscription:  # noqa
            return None
        if user.subscription.subscription_plan.name == 'standard':  # noqa
            return self.queryset.filter(is_premium=False)
        return self.queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Edenthought | Articles'
        return context


class ArticleDetailView(LoginRequiredMixin, DetailView):
    login_url = 'login'
    redirect_field_name = 'redirect_to'

    model = Article
    template_name = 'client/article-detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Edenthought | {self.get_object().title}'
        return context


class SubscriptionPlansView(LoginRequiredMixin, TemplateView):
    login_url = 'login'
    redirect_field_name = 'redirect_to'

    template_name = 'client/subscription-plans.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Edenthought | Subscription Plans'
        return context


class CreateSubscriptionView(LoginRequiredMixin, RedirectView):
    login_url = 'login'
    redirect_field_name = 'redirect_to'
    pattern_name = 'client:dashboard'

    def get_redirect_url(self, *args, **kwargs):
        user = self.request.user
        sub_id = self.request.GET.get('subID')
        plan_name = self.request.GET.get('plan')
        plan = get_object_or_404(SubscriptionPlan, name=plan_name)

        try:
            Subscription.objects.create(
                user=user,
                subscriber_name=user.full_name(),  # noqa
                subscription_plan=plan,
                paypal_subscription_id=sub_id,
                is_active=True
            )
            messages.success(self.request, 'Subscription created successfully!')

        except IntegrityError:
            messages.error(
                self.request,
                'Subscription not created! Invalid data has been submitted.'
            )
        except Exception as e:
            messages.error(self.request, f'Something went wrong!\n{e}')

        return super().get_redirect_url(*args, **kwargs)


class DeleteSubscriptionView(TemplateView):
    template_name = 'client/delete-subscription.html'

    @method_decorator(login_required(
        login_url='login',
        redirect_field_name='redirect_to'
    ))
    def dispatch(self, request, *args, **kwargs):
        sub_id = self.kwargs.get('subID')

        return super(DeleteSubscriptionView, self).dispatch(
            request,
            sub_id,
            *args,
            **kwargs
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Edenthought | Delete Subscription'

        sub_id = self.kwargs.get('subID')

        # Delete subscription from PayPal
        access_token = get_access_token()

        try:
            cancel_subscription_paypal(access_token, sub_id)
        except SubscriptionNotDeletedException:
            context['is_deleted'] = False

        else:
            # Delete subscription from Django (application side)
            subscription = get_object_or_404(
                Subscription,
                user=self.request.user,
                paypal_subscription_id=sub_id
            )
            subscription.delete()
            context['is_deleted'] = True

        return context


class UpdateSubscriptionView(LoginRequiredMixin, RedirectView):
    login_url = 'login'
    redirect_field_name = 'redirect_to'
    pattern_name = 'account'

    def dispatch(self, request, *args, **kwargs):
        sub_id = self.kwargs.get('subID')

        return super().dispatch(
            request,
            sub_id,
            *args,
            **kwargs
        )

    def get_redirect_url(self, *args, **kwargs):
        access_token = get_access_token()
        approve_link = update_subscription_paypal(
            access_token,
            sub_id=self.kwargs.get('subID')
        )
        if approve_link:
            messages.success(self.request, 'Subscription updated successfully!')
            return redirect(approve_link)

        messages.error(self.request, 'Something went wrong!')
        return super().get_redirect_url(*args, **kwargs)


class PayPalSubConfirmedView(LoginRequiredMixin, TemplateView):
    login_url = 'login'
    redirect_field_name = 'redirect_to'
    template_name = 'client/paypal-update-confirmed.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'PayPal Confirmed Subscription'

        subscription = Subscription.objects.filter(user=self.request.user)
        if subscription.exists():
            context['subID'] = subscription[0].paypal_subscription_id

        return context


class DjangoSubConfirmedView(TemplateView):
    template_name = 'client/django-update-confirmed.html'

    @method_decorator(login_required(
        login_url='login',
        redirect_field_name='redirect_to'
    ))
    def dispatch(self, request, *args, **kwargs):
        sub_id = self.kwargs.get('subID')

        return super().dispatch(
            request,
            sub_id,
            *args,
            **kwargs
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Subscription Confirmed'

        subscription = get_object_or_404(
            Subscription,
            user=self.request.user,
            paypal_subscription_id=self.kwargs.get('subID')
        )
        access_token = get_access_token()
        paypal_subscription_plan_id = get_current_subscription_plan(
            access_token,
            self.kwargs['subID']
        )
        current_subscription_plan_id = subscription.subscription_plan.paypal_plan_id

        if paypal_subscription_plan_id != current_subscription_plan_id:
            new_plan = get_object_or_404(
                SubscriptionPlan,
                paypal_plan_id=paypal_subscription_plan_id
            )

            subscription.subscription_plan = new_plan
            subscription.save()

        context['subPlan'] = subscription.subscription_plan

        return context

client/templates/client/includes/client_menu.html
<ul class="navbar-nav">

  <li class="nav-item">
    <a class="btn btn-secondary navbar-btn"
       type="button"
       href="{% url 'client:dashboard' %}">

      Dashboard

    </a>
  </li>

  <li class="nav-item">
    <a class="btn btn-secondary navbar-btn"
       type="button"
       href="{% url 'client:browse-articles' %}">

      Browse articles

    </a>
  </li>

  <li class="nav-item">
    <a class="btn btn-secondary navbar-btn"
       type="button"
       href="{% url 'client:subscription-plans' %}">

      Pricing

    </a>
  </li>

  <li class="nav-item">
    <a class="btn btn-secondary navbar-btn"
       type="button"
       href="{% url 'account' %}">

      Account

    </a>
  </li>

  <li class="nav-item">
    <a class="btn btn-secondary navbar-btn"
       type="button"
       href="{% url 'logout' %}">

      Logout

    </a>
  </li>

  </ul>

client/templates/client/includes/delete_sub_modal.html
<div class="modal fade" id="deleteSubModal" tabindex="-1" role="dialog" aria-labelledby="deleteSubModalTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header justify-content-sm-between">
        <h5 class="modal-title" id="exampleModalLongTitle">Delete Subscription</h5>
        <button type="button" class="close btn-close" data-dismiss="modal" aria-label="Close">
        </button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete this subscription?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <a type="button" class="btn btn-danger" href="{% url 'client:delete-subscription' subID=user.subscription.paypal_subscription_id %}">Delete</a>
      </div>
    </div>
  </div>
</div>

client/templates/client/includes/update_sub_modal.html
<div class="modal fade" id="updateSubModal" tabindex="-1" role="dialog" aria-labelledby="updateSubModalTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header justify-content-sm-between">
        <h5 class="modal-title" id="exampleModalLongTitle">Update Subscription</h5>
        <button type="button" class="close btn-close" data-dismiss="modal" aria-label="Close">
        </button>
      </div>
      <div class="modal-body">
        Are you sure you want to
        {% if user.subscription.subscription_plan.name == 'standard'%}
          upgrade your subscription plan to Premium?
        {% else %}
          downgrade your subscription plan to Standard?
        {% endif %}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <a type="button" class="btn btn-info" href="{% url 'client:update-subscription' subID=user.subscription.paypal_subscription_id %}">Update</a>
      </div>
    </div>
  </div>
</div>